### ISSUE TITLE
最新的docker 2.2.1 提示出错 

### ISSUE THREAD

**Issue by yilin101** [SuperNG6/docker-subfinder#14]
Traceback (most recent call last):
  File "/usr/local/bin/subfinder", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/subfinder/run_gevent.py", line 13, in run
    run_(SubFinder)
  File "/usr/local/lib/python3.6/site-packages/subfinder/run.py", line 103, in run
    new_method = [find_method(m) for m in method]
  File "/usr/local/lib/python3.6/site-packages/subfinder/run.py", line 103, in <listcomp>
    new_method = [find_method(m) for m in method]
  File "/usr/local/lib/python3.6/site-packages/subfinder/run.py", line 18, in find_method
    raise argparse.ArgumentTypeError('Cant found SubSearcher named {}'.format(m))
argparse.ArgumentTypeError: Cant found SubSearcher named zimuzu
==============本轮搜索已结束，下次遍历为1d后==============

群晖 docker
2.0.2可以正常使用

**Comment by carlchina** [comment]
同上 问题 下载老版本可以运行

**Comment by SuperNG6** [comment]
换这个
https://github.com/allanpk716/ChineseSubFinder

**Comment by yilin101** [comment]
> 换这个
> https://github.com/allanpk716/ChineseSubFinder

我试一下 感谢

**Comment by yilin101** [comment]
> 同上 问题 下载老版本可以运行

到config 把zimuzu相关配置删掉就行了
